// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authzmw.proto

package org.example.grpc;

public final class Authzmw {
  private Authzmw() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authz_CheckPermissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authz_CheckPermissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authz_CheckPermissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authz_CheckPermissionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rauthzmw.proto\022\005authz\"F\n\026CheckPermissio" +
      "nRequest\022\016\n\006userId\030\001 \001(\005\022\014\n\004path\030\002 \001(\t\022\016" +
      "\n\006method\030\003 \001(\t\";\n\027CheckPermissionRespons" +
      "e\022\017\n\007allowed\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2`\n\014A" +
      "uthzService\022P\n\017CheckPermission\022\035.authz.C" +
      "heckPermissionRequest\032\036.authz.CheckPermi" +
      "ssionResponseB\024\n\020org.example.grpcP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_authz_CheckPermissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authz_CheckPermissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authz_CheckPermissionRequest_descriptor,
        new java.lang.String[] { "UserId", "Path", "Method", });
    internal_static_authz_CheckPermissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authz_CheckPermissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authz_CheckPermissionResponse_descriptor,
        new java.lang.String[] { "Allowed", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
