// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface CreateRefreshTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.CreateRefreshTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string refresh_token = 1;</code>
   * @return The refreshToken.
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refresh_token = 1;</code>
   * @return The bytes for refreshToken.
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();

  /**
   * <code>int64 valid_until = 2;</code>
   * @return The validUntil.
   */
  long getValidUntil();
}
