// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface IsValidRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.IsValidRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
