// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface RotateRefreshTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.RotateRefreshTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string old_token = 1;</code>
   * @return The oldToken.
   */
  java.lang.String getOldToken();
  /**
   * <code>string old_token = 1;</code>
   * @return The bytes for oldToken.
   */
  com.google.protobuf.ByteString
      getOldTokenBytes();

  /**
   * <code>int32 user_id = 2;</code>
   * @return The userId.
   */
  int getUserId();
}
