// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface GenerateAccessTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.GenerateAccessTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_token = 1;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 1;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <pre>
   * unix timestamp
   * </pre>
   *
   * <code>int64 expires_at = 2;</code>
   * @return The expiresAt.
   */
  long getExpiresAt();
}
