// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public final class TokenServiceProto {
  private TokenServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_GenerateAccessTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_GenerateAccessTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_GenerateAccessTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_GenerateAccessTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_ValidateAccessTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_ValidateAccessTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_ValidateAccessTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_ValidateAccessTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_CreateRefreshTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_CreateRefreshTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_CreateRefreshTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_CreateRefreshTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_RotateRefreshTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_RotateRefreshTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_RotateRefreshTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_RotateRefreshTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_RevokeTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_RevokeTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_RevokeTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_RevokeTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_RevokeAllTokensOfUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_RevokeAllTokensOfUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_RevokeAllTokensOfUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_RevokeAllTokensOfUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_IsValidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_IsValidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_service_IsValidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_service_IsValidResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023token_service.proto\022\rtoken.service\"-\n\032" +
      "GenerateAccessTokenRequest\022\017\n\007user_id\030\001 " +
      "\001(\005\"G\n\033GenerateAccessTokenResponse\022\024\n\014ac" +
      "cess_token\030\001 \001(\t\022\022\n\nexpires_at\030\002 \001(\003\"2\n\032" +
      "ValidateAccessTokenRequest\022\024\n\014access_tok" +
      "en\030\001 \001(\t\"=\n\033ValidateAccessTokenResponse\022" +
      "\r\n\005valid\030\001 \001(\010\022\017\n\007user_id\030\002 \001(\005\",\n\031Creat" +
      "eRefreshTokenRequest\022\017\n\007user_id\030\001 \001(\005\"H\n" +
      "\032CreateRefreshTokenResponse\022\025\n\rrefresh_t" +
      "oken\030\001 \001(\t\022\023\n\013valid_until\030\002 \001(\003\"?\n\031Rotat" +
      "eRefreshTokenRequest\022\021\n\told_token\030\001 \001(\t\022" +
      "\017\n\007user_id\030\002 \001(\005\"D\n\032RotateRefreshTokenRe" +
      "sponse\022\021\n\tnew_token\030\001 \001(\t\022\023\n\013valid_until" +
      "\030\002 \001(\003\"#\n\022RevokeTokenRequest\022\r\n\005token\030\001 " +
      "\001(\t\"&\n\023RevokeTokenResponse\022\017\n\007success\030\001 " +
      "\001(\010\"/\n\034RevokeAllTokensOfUserRequest\022\017\n\007u" +
      "ser_id\030\001 \001(\005\"6\n\035RevokeAllTokensOfUserRes" +
      "ponse\022\025\n\rrevoked_count\030\001 \001(\005\"\037\n\016IsValidR" +
      "equest\022\r\n\005token\030\001 \001(\t\"F\n\017IsValidResponse" +
      "\022\r\n\005valid\030\001 \001(\010\022\017\n\007user_id\030\002 \001(\005\022\023\n\013vali" +
      "d_until\030\003 \001(\0032\360\001\n\022AccessTokenService\022l\n\023" +
      "GenerateAccessToken\022).token.service.Gene" +
      "rateAccessTokenRequest\032*.token.service.G" +
      "enerateAccessTokenResponse\022l\n\023ValidateAc" +
      "cessToken\022).token.service.ValidateAccess" +
      "TokenRequest\032*.token.service.ValidateAcc" +
      "essTokenResponse2\377\003\n\023RefreshTokenService" +
      "\022i\n\022CreateRefreshToken\022(.token.service.C" +
      "reateRefreshTokenRequest\032).token.service" +
      ".CreateRefreshTokenResponse\022i\n\022RotateRef" +
      "reshToken\022(.token.service.RotateRefreshT" +
      "okenRequest\032).token.service.RotateRefres" +
      "hTokenResponse\022T\n\013RevokeToken\022!.token.se" +
      "rvice.RevokeTokenRequest\032\".token.service" +
      ".RevokeTokenResponse\022r\n\025RevokeAllTokensO" +
      "fUser\022+.token.service.RevokeAllTokensOfU" +
      "serRequest\032,.token.service.RevokeAllToke" +
      "nsOfUserResponse\022H\n\007IsValid\022\035.token.serv" +
      "ice.IsValidRequest\032\036.token.service.IsVal" +
      "idResponseB\'\n\020org.example.grpcB\021TokenSer" +
      "viceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_token_service_GenerateAccessTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_token_service_GenerateAccessTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_GenerateAccessTokenRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_token_service_GenerateAccessTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_token_service_GenerateAccessTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_GenerateAccessTokenResponse_descriptor,
        new java.lang.String[] { "AccessToken", "ExpiresAt", });
    internal_static_token_service_ValidateAccessTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_token_service_ValidateAccessTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_ValidateAccessTokenRequest_descriptor,
        new java.lang.String[] { "AccessToken", });
    internal_static_token_service_ValidateAccessTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_token_service_ValidateAccessTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_ValidateAccessTokenResponse_descriptor,
        new java.lang.String[] { "Valid", "UserId", });
    internal_static_token_service_CreateRefreshTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_token_service_CreateRefreshTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_CreateRefreshTokenRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_token_service_CreateRefreshTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_token_service_CreateRefreshTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_CreateRefreshTokenResponse_descriptor,
        new java.lang.String[] { "RefreshToken", "ValidUntil", });
    internal_static_token_service_RotateRefreshTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_token_service_RotateRefreshTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_RotateRefreshTokenRequest_descriptor,
        new java.lang.String[] { "OldToken", "UserId", });
    internal_static_token_service_RotateRefreshTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_token_service_RotateRefreshTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_RotateRefreshTokenResponse_descriptor,
        new java.lang.String[] { "NewToken", "ValidUntil", });
    internal_static_token_service_RevokeTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_token_service_RevokeTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_RevokeTokenRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_token_service_RevokeTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_token_service_RevokeTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_RevokeTokenResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_token_service_RevokeAllTokensOfUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_token_service_RevokeAllTokensOfUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_RevokeAllTokensOfUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_token_service_RevokeAllTokensOfUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_token_service_RevokeAllTokensOfUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_RevokeAllTokensOfUserResponse_descriptor,
        new java.lang.String[] { "RevokedCount", });
    internal_static_token_service_IsValidRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_token_service_IsValidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_IsValidRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_token_service_IsValidResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_token_service_IsValidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_service_IsValidResponse_descriptor,
        new java.lang.String[] { "Valid", "UserId", "ValidUntil", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
