// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface ValidateAccessTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.ValidateAccessTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <code>int32 user_id = 2;</code>
   * @return The userId.
   */
  int getUserId();
}
