// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authzmw.proto

package org.example.grpc;

public interface CheckPermissionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authz.CheckPermissionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool allowed = 1;</code>
   * @return The allowed.
   */
  boolean getAllowed();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
