// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface CreateRefreshTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.CreateRefreshTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
