// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: otp_service.proto

package org.example.grpc;

public interface GenerateOtpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:otp.service.GenerateOtpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string transaction_id = 2;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 2;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>int32 expiry_minutes = 3;</code>
   * @return The expiryMinutes.
   */
  int getExpiryMinutes();
}
