// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: otp_service.proto

package org.example.grpc;

public interface GenerateOtpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:otp.service.GenerateOtpResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string otp_code = 1;</code>
   * @return The otpCode.
   */
  java.lang.String getOtpCode();
  /**
   * <code>string otp_code = 1;</code>
   * @return The bytes for otpCode.
   */
  com.google.protobuf.ByteString
      getOtpCodeBytes();
}
