// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: otp_service.proto

package org.example.grpc;

public final class OtpServiceProto {
  private OtpServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_otp_service_GenerateOtpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_otp_service_GenerateOtpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_otp_service_GenerateOtpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_otp_service_GenerateOtpResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_otp_service_ValidateOtpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_otp_service_ValidateOtpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_otp_service_ValidateOtpResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_otp_service_ValidateOtpResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021otp_service.proto\022\013otp.service\"R\n\022Gene" +
      "rateOtpRequest\022\014\n\004type\030\001 \001(\t\022\026\n\016transact" +
      "ion_id\030\002 \001(\t\022\026\n\016expiry_minutes\030\003 \001(\005\"\'\n\023" +
      "GenerateOtpResponse\022\020\n\010otp_code\030\001 \001(\t\"L\n" +
      "\022ValidateOtpRequest\022\014\n\004type\030\001 \001(\t\022\026\n\016tra" +
      "nsaction_id\030\002 \001(\t\022\020\n\010otp_code\030\003 \001(\t\"$\n\023V" +
      "alidateOtpResponse\022\r\n\005valid\030\001 \001(\0102\260\001\n\nOt" +
      "pService\022P\n\013GenerateOtp\022\037.otp.service.Ge" +
      "nerateOtpRequest\032 .otp.service.GenerateO" +
      "tpResponse\022P\n\013ValidateOtp\022\037.otp.service." +
      "ValidateOtpRequest\032 .otp.service.Validat" +
      "eOtpResponseB%\n\020org.example.grpcB\017OtpSer" +
      "viceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_otp_service_GenerateOtpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_otp_service_GenerateOtpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_otp_service_GenerateOtpRequest_descriptor,
        new java.lang.String[] { "Type", "TransactionId", "ExpiryMinutes", });
    internal_static_otp_service_GenerateOtpResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_otp_service_GenerateOtpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_otp_service_GenerateOtpResponse_descriptor,
        new java.lang.String[] { "OtpCode", });
    internal_static_otp_service_ValidateOtpRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_otp_service_ValidateOtpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_otp_service_ValidateOtpRequest_descriptor,
        new java.lang.String[] { "Type", "TransactionId", "OtpCode", });
    internal_static_otp_service_ValidateOtpResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_otp_service_ValidateOtpResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_otp_service_ValidateOtpResponse_descriptor,
        new java.lang.String[] { "Valid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
