// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

/**
 * Protobuf type {@code token.service.RevokeAllTokensOfUserResponse}
 */
public final class RevokeAllTokensOfUserResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:token.service.RevokeAllTokensOfUserResponse)
    RevokeAllTokensOfUserResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RevokeAllTokensOfUserResponse.newBuilder() to construct.
  private RevokeAllTokensOfUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RevokeAllTokensOfUserResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RevokeAllTokensOfUserResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RevokeAllTokensOfUserResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            revokedCount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.grpc.TokenServiceProto.internal_static_token_service_RevokeAllTokensOfUserResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.grpc.TokenServiceProto.internal_static_token_service_RevokeAllTokensOfUserResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.grpc.RevokeAllTokensOfUserResponse.class, org.example.grpc.RevokeAllTokensOfUserResponse.Builder.class);
  }

  public static final int REVOKED_COUNT_FIELD_NUMBER = 1;
  private int revokedCount_;
  /**
   * <code>int32 revoked_count = 1;</code>
   * @return The revokedCount.
   */
  @java.lang.Override
  public int getRevokedCount() {
    return revokedCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (revokedCount_ != 0) {
      output.writeInt32(1, revokedCount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (revokedCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, revokedCount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.grpc.RevokeAllTokensOfUserResponse)) {
      return super.equals(obj);
    }
    org.example.grpc.RevokeAllTokensOfUserResponse other = (org.example.grpc.RevokeAllTokensOfUserResponse) obj;

    if (getRevokedCount()
        != other.getRevokedCount()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REVOKED_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRevokedCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.grpc.RevokeAllTokensOfUserResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.grpc.RevokeAllTokensOfUserResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code token.service.RevokeAllTokensOfUserResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:token.service.RevokeAllTokensOfUserResponse)
      org.example.grpc.RevokeAllTokensOfUserResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.grpc.TokenServiceProto.internal_static_token_service_RevokeAllTokensOfUserResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.grpc.TokenServiceProto.internal_static_token_service_RevokeAllTokensOfUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.grpc.RevokeAllTokensOfUserResponse.class, org.example.grpc.RevokeAllTokensOfUserResponse.Builder.class);
    }

    // Construct using org.example.grpc.RevokeAllTokensOfUserResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      revokedCount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.grpc.TokenServiceProto.internal_static_token_service_RevokeAllTokensOfUserResponse_descriptor;
    }

    @java.lang.Override
    public org.example.grpc.RevokeAllTokensOfUserResponse getDefaultInstanceForType() {
      return org.example.grpc.RevokeAllTokensOfUserResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.grpc.RevokeAllTokensOfUserResponse build() {
      org.example.grpc.RevokeAllTokensOfUserResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.grpc.RevokeAllTokensOfUserResponse buildPartial() {
      org.example.grpc.RevokeAllTokensOfUserResponse result = new org.example.grpc.RevokeAllTokensOfUserResponse(this);
      result.revokedCount_ = revokedCount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.grpc.RevokeAllTokensOfUserResponse) {
        return mergeFrom((org.example.grpc.RevokeAllTokensOfUserResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.grpc.RevokeAllTokensOfUserResponse other) {
      if (other == org.example.grpc.RevokeAllTokensOfUserResponse.getDefaultInstance()) return this;
      if (other.getRevokedCount() != 0) {
        setRevokedCount(other.getRevokedCount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.example.grpc.RevokeAllTokensOfUserResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.example.grpc.RevokeAllTokensOfUserResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int revokedCount_ ;
    /**
     * <code>int32 revoked_count = 1;</code>
     * @return The revokedCount.
     */
    @java.lang.Override
    public int getRevokedCount() {
      return revokedCount_;
    }
    /**
     * <code>int32 revoked_count = 1;</code>
     * @param value The revokedCount to set.
     * @return This builder for chaining.
     */
    public Builder setRevokedCount(int value) {
      
      revokedCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 revoked_count = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevokedCount() {
      
      revokedCount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:token.service.RevokeAllTokensOfUserResponse)
  }

  // @@protoc_insertion_point(class_scope:token.service.RevokeAllTokensOfUserResponse)
  private static final org.example.grpc.RevokeAllTokensOfUserResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.grpc.RevokeAllTokensOfUserResponse();
  }

  public static org.example.grpc.RevokeAllTokensOfUserResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RevokeAllTokensOfUserResponse>
      PARSER = new com.google.protobuf.AbstractParser<RevokeAllTokensOfUserResponse>() {
    @java.lang.Override
    public RevokeAllTokensOfUserResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RevokeAllTokensOfUserResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RevokeAllTokensOfUserResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RevokeAllTokensOfUserResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.grpc.RevokeAllTokensOfUserResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

