// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface RevokeTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.RevokeTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
