// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface RevokeAllTokensOfUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.RevokeAllTokensOfUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 revoked_count = 1;</code>
   * @return The revokedCount.
   */
  int getRevokedCount();
}
