// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token_service.proto

package org.example.grpc;

public interface RotateRefreshTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token.service.RotateRefreshTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string new_token = 1;</code>
   * @return The newToken.
   */
  java.lang.String getNewToken();
  /**
   * <code>string new_token = 1;</code>
   * @return The bytes for newToken.
   */
  com.google.protobuf.ByteString
      getNewTokenBytes();

  /**
   * <code>int64 valid_until = 2;</code>
   * @return The validUntil.
   */
  long getValidUntil();
}
