// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: otp_service.proto

package org.example.grpc;

public interface ValidateOtpResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:otp.service.ValidateOtpResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  boolean getValid();
}
