// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: otp_service.proto

package org.example.grpc;

public interface ValidateOtpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:otp.service.ValidateOtpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string transaction_id = 2;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transaction_id = 2;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string otp_code = 3;</code>
   * @return The otpCode.
   */
  java.lang.String getOtpCode();
  /**
   * <code>string otp_code = 3;</code>
   * @return The bytes for otpCode.
   */
  com.google.protobuf.ByteString
      getOtpCodeBytes();
}
